name: "Run Tests"
on: [push]
jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: PHP Configuration
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: pecl
          extensions: pcov
      - name: Copy ENV Configuration
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install --prefer-dist --dev --no-interaction
      - name: Generate Application Key
        run: php artisan key:generate
      - name: Create SQLite DB & Run Migrations
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: |
          mkdir -p database
          touch database/database.sqlite
          php artisan migrate
      - name: Run Tests
        run: vendor/bin/phpunit --coverage-text --testdox --coverage-clover build/logs/clover.xml
      - name: Check Code Coverage
        run: |
          php coverage-checker.php build/logs/clover.xml
